const ONE_THOUSAND = 1000;
const ONE_MILLION = ONE_THOUSAND * 1000;
const ONE_BILLION = ONE_MILLION * 1000;
const ONE_TRILLION = ONE_BILLION * 1000;
const ONE_QUADRILLION = ONE_TRILLION * 1000;
const ONE_QUINTILLION = ONE_QUADRILLION * 1000;
const ONE_SEXTILLION = ONE_QUINTILLION * 1000;
const ONE_SEPTILLION = ONE_SEXTILLION * 1000;

export {
  ONE_THOUSAND,
  ONE_MILLION,
  ONE_BILLION,
  ONE_TRILLION,
  ONE_QUADRILLION,
  ONE_QUINTILLION,
  ONE_SEXTILLION,
  ONE_SEPTILLION
};
